### ISSUE TITLE
Exit code 1 whith gitlab ci build

### ISSUE THREAD

**Issue by Armays** [npm/npm#15841]
Hello, my Gitlab CI build fails both for the front and the back repositories which are in full JS. Each time it's because of npm install. For the front it's because of node-sass and for the back it's because of phantomjs. I dont understand because when i npm i from my docker image it works and i dont have any error, and when i build i have error code 1.

Here is my .gitlab-ci.yml file : 
```
image: ***

stages:
  - build
  - test
  - deploy

variables:
  BUILD_IMG: $CI_REGISTRY_IMAGE:$CI_BUILD_REF
  TEST_IMG: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  RELEASE_IMG: $CI_REGISTRY_IMAGE:latest
  AWS_STAGING_ENV: "***"
  AWS_PROD_ENV: "***"
  DOCKERRUN: Dockerrun.aws.json
  DEPLOY_ARCHIVE: ${AWS_APP}-${CI_BUILD_REF}.zip

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - .ci/before_script

build:
  stage: build
  script:
  - docker build --pull -t $BUILD_IMG .
  - docker push $BUILD_IMG

test:
  stage: test
  script:
  - docker pull $BUILD_IMG
  - docker run --rm $BUILD_IMG npm run test
  - docker tag $BUILD_IMG $TEST_IMG
  - docker push $TEST_IMG

deploy:staging:
  stage: deploy
  environment: Staging
  variables:
    DOCKER_IMG: ${CI_REGISTRY_IMAGE}:${CI_BUILD_REF}
  script:
  - ./.ci/create-deploy-archive $DOCKER_IMG $AWS_BUCKET $DOCKERRUN $DEPLOY_ARCHIVE
  - ./.ci/aws-deploy $DEPLOY_ARCHIVE $CI_BUILD_REF $AWS_STAGING_ENV
  artifacts:
    paths:
    - $DEPLOY_ARCHIVE
  except:
  - production

deploy:production:
  stage: deploy
  environment: Production
  variables:
    DOCKER_IMG: ${CI_REGISTRY_IMAGE}:latest
  script:
  - .ci/push-new-image $TEST_IMG $RELEASE_IMG
  - .ci/create-deploy-archive $DOCKER_IMG $AWS_BUCKET $DOCKERRUN $DEPLOY_ARCHIVE
  - .ci/aws-deploy $DEPLOY_ARCHIVE $CI_BUILD_REF $AWS_PROD_ENV
  artifacts:
    paths:
    - $DEPLOY_ARCHIVE
  only:
  - production
  when: manual
```
Here is the verbose mode for node sass : 
```
npm info install node-sass@4.5.0
Binary found at /formation-front/node_modules/node-sass/vendor/linux-x64-51/binding.node
Testing binary
Binary is fine
npm verb lifecycle node-sass@3.13.1~postinstall: unsafe-perm in lifecycle false
npm verb lifecycle node-sass@3.13.1~postinstall: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/formation-front/node_modules/node-sass/node_modules/.bin:/formation-front/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle node-sass@3.13.1~postinstall: CWD: /formation-front/node_modules/node-sass
sr/bin:/sbin:/bin
npm verb lifecycle node-sass@3.13.1~postinstall: CWD: /formation-front/node_modules/node-sass
```

Here is the output for phantomjs : 
```
npm info lifecycle phantomjs-prebuilt@2.1.14~install: phantomjs-prebuilt@2.1.14

phantomjs-prebuilt@2.1.14 install /formation-back/node_modules/html-pdf/node_modules/phantomjs-prebuilt
node install.js
```

#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

#### What's going wrong?
My Gitlab CI build fails with exit code 1 for the frant because of node-sass and for the back because of phantomjs.
#### How can the CLI team reproduce the problem?

npm install of this packages.json : 

### supporting information:

 - `npm -v` prints: 3
 - `node -v` prints: 7.4
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Debian(Jessie)
 - Network issues:
   - Geographic location where npm was run:
  From Francfort with the gitlab runner hosted on an amzon server linux AMI
 - Container:
   - [ ] I develop / deploy using Docker.

**Comment by ashleygwilliams** [comment]
closing as we chatted on IRC. please reopen if you have any more difficulty or feel free to ping me on IRC!

**Comment by joshnoe** [comment]
Would have been nice to post the solution to this issue

**Comment by ashleygwilliams** [comment]
reopening as @Armays contacted me to let me know they were still running into the issue!

**Comment by zourtney** [comment]
**EDIT**: this workaround is no longer needed. I'm not sure why

----

**Original comment:**

At what stage is `npm install` getting run? I encountered a similar issue today, and skirted around it by:

1. moving `npm install` to the `before_script` phase
2. installing `node-sass` separately, before other modules (seems necessary, not sure why)

```yml
image: node:latest

before_script:
  - apt-get -qq update && apt-get -qq -y install bzip2
  - npm install phantomjs-prebuilt
  - npm install node-sass
  - npm install

all_tests:
  script: npm test
```

See [this StackOverflow answer](http://stackoverflow.com/a/33525995/311207) and [this Github issue](https://github.com/Medium/phantomjs/issues/659#issuecomment-268119362).

Your setup to a lot more complex than mine, but maybe something in there can point you in the right direction.
