### ISSUE TITLE
NPM installs peerDependencies of devDependencies when --production flag is on

### ISSUE THREAD

**Issue by wheresrhys** [npm/npm#5704]
(All files written as yaml to save time)
### package.json

``` yaml
dependencies:
   module1: 0.1.0
devDependencies:
   module2: 0.1.0
```
### module2/package.json

``` yaml
peerDependencies:
   module3: 0.1.0
```

Command `npm install --production`
Expected - only module1 is installed
Result  - module1 and module 3 are installed
