### ISSUE TITLE
Can't auto-deploy from travis-ci

### ISSUE THREAD

**Issue by janpaepke** [npm/npm#7914]
Hi guys.

For some reason the auto-deploy from travis fails.
If I publish locally everything works fine.
Can it have something to do with the fact, that I'm just contributor, not owner of the git repository?

here's the log from travis:

```
Installing deploy dependencies

Preparing deploy
Authenticated with email e-mail@janpaepke.de
/usr/lib/git-core/git-stash: 186: /usr/lib/git-core/git-stash: cannot create /home/travis/build/mathiasbynens/jquery-visibility/.git/logs/refs/stash: Directory nonexistent

Deploying application
npm ERR! publish Failed PUT 500
npm ERR! Linux 2.6.32-042stab094.7
npm ERR! argv "/home/travis/.nvm/versions/node/v0.12.2/bin/node" "/home/travis/.nvm/versions/node/v0.12.2/bin/npm" "publish"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code E500

npm ERR! unexpected status code: 401 : jquery-visibility
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/mathiasbynens/jquery-visibility/npm-debug.log

No stash found.

Done. Your build exited with 0.
```

Here's my `.travis.yml` config file:

```
language: node_js
node_js:
- stable
script: node ./node_modules/gulp/bin/gulp
notifications:
  email: false
deploy:
  provider: npm
  email: e-mail@janpaepke.de
  api_key:
    secure: *key*
  on:
    tags: true
```

Can anyone provide any insights on this?
